var lang = {
	_T: function(s,n1,n2,n3,n4,n5){
		if(!Check.isEmpty(lang[config.lang][s])){
			s = lang[config.lang][s];
		}
		if(!Check.isEmpty(n1)){s = s.replace(/%VAL1%/gi,n1);}
		if(!Check.isEmpty(n2)){s = s.replace(/%VAL2%/gi,n2);}
		if(!Check.isEmpty(n3)){s = s.replace(/%VAL3%/gi,n3);}
		if(!Check.isEmpty(n4)){s = s.replace(/%VAL4%/gi,n4);}
		if(!Check.isEmpty(n5)){s = s.replace(/%VAL5%/gi,n5);}
		return s;
		
	},
	en: {
	
		/**/
		'Metal'								: 'Metal',
		'Crystal'							: 'Crystal',
		'Deuterium'							: 'Deuterium',
		'Darkmatter'						: 'Dark Matter',
		'Energy'							: 'Energy',
		'Messages'							: 'Messages',
		'write_message'						: 'Write Message',
		
		'type_mission_1'  					: 'Attack',
		'type_mission_2'  					: 'ACS Attack',
		'type_mission_3'  					: 'Transport',
		'type_mission_4'  					: 'Deploy',
		'type_mission_5'  					: 'Hold Position',
		'type_mission_6'  					: 'Spy',
		'type_mission_7'  					: 'Colonize',
		'type_mission_8'  					: 'Recycle',
		'type_mission_9'  					: 'Destroy',
		'type_mission_15' 					: 'Expedition',
		
		'user_level_0' : 'Player',
		'user_level_1' : 'Moderator',
		'user_level_2' : 'Operator',
		'user_level_3' : 'Administrator',
		
		'see_you_soon'						: 'See you soon!',
		'page_doesnt_exist'					: 'The page you requested does not exist',
		
		
		'tech_rc_202' : "S. cargo",
		'tech_rc_203' : "L. cargo",
		'tech_rc_204' : "F. Light",
		'tech_rc_205' : "F. Heavy",
		'tech_rc_206' : "Cruiser",
		'tech_rc_207' : "Battleship",
		'tech_rc_208' : "Col. Ship",
		'tech_rc_209' : "Recycler",
		'tech_rc_210' : "Probes",
		'tech_rc_211' : "Bomber",
		'tech_rc_212' : "S. Satellite",
		'tech_rc_213' : "Destroyer",
		'tech_rc_214' : "Deathstar",
		'tech_rc_215' : "Battlecru.",
		'tech_rc_216' : "UFO",
		'tech_rc_401' : "Rocket L.",
		'tech_rc_402' : "Light L.",
		'tech_rc_403' : "Heavy L.",
		'tech_rc_404' : "Gauss C.",
		'tech_rc_405' : "Ion C.",
		'tech_rc_406' : "Plasma T.",
		'tech_rc_407' : "S. Dome",
		'tech_rc_408' : "L. Dome",
		
		
		'tn_vacation_mode'					: 'Vacation mode active until ',
		'tn_vacation_mode_active' 			: "Vacation mode active", 
		'tn_delete_mode'					: 'Your account is in erase mode. The same will be deleted the ',
		
		'lm_overview'						: 'Overview',
		'lm_galaxy'							: 'Galaxy',
		'lm_empire'							: 'Empire',
		'lm_fleet'							: 'Fleet',
		'lm_buildings'						: 'Buildings',
		'lm_research'						: 'Research',
		'lm_shipshard'						: 'Shipyard',
		'lm_defenses'						: 'Defense',
		'lm_resources'						: 'Resources',
		'lm_officiers'						: 'Officers',
		'lm_trader'							: 'Merchant',
		'lm_technology'						: 'Technology',
		'lm_messages'						: 'Messages',
		'lm_alliance'						: 'Alliance',
		'lm_buddylist'						: 'Buddylist',
		'lm_notes'							: 'Notes',
		'lm_statistics'						: 'Statistics',
		'lm_search'							: 'Search',
		'lm_options'						: 'Options',
		'lm_banned'							: 'Banned',
		'lm_contact'						: 'Contact',
		'lm_forums'							: 'Forum',
		'lm_logout'							: 'Logout',
		'lm_administration'					: 'Administration',
		'lm_game_speed'						: 'Game',
		'lm_fleet_speed'					: 'Fleets',
		'lm_resources_speed'				: 'Resources',
		'lm_queues'							: 'Queues',
		
		
		'ov_newname_error'					: 'You entered an illegal character. You can only enter alphanumeric characters.',
		'ov_planet_abandoned'				: 'Abandoned planet successfully',
		'ov_principal_planet_cant_abanone'	: 'You are not able to delete your main planet!',
		'ov_wrong_pass'						: 'Incorrect password, enter it again.',
		'ov_have_new_message'				: 'You have 1 new message',
		'ov_have_new_messages'				: 'You have %m new messages',
		'ov_free'							: 'Free',
		'ov_news'							: 'News',
		'ov_place'							: 'Rank',
		'ov_of'								: 'of',
		'ov_planet'							: 'Planet',
		'ov_server_time'					: 'Server time ',
		'ov_events'							: 'Events',
		'ov_diameter'						: 'Diameter',
		'ov_distance_unit'					: 'km',
		'ov_temperature'					: 'Temperature',
		'ov_aprox'							: 'approx.',
		'ov_temp_unit'						: '&#186,C',
		'ov_to'								: 'to',
		'ov_position'						: 'Position',
		'ov_points'							: 'Points',
		'ov_security_request'				: 'Security query',
		'ov_security_confirm'				: 'Please confirm planet deletion.',
		'ov_with_pass'						: 'by entering your password',
		'ov_password'						: 'Password',
		'ov_delete_planet'					: 'Delete planet!',
		'ov_your_planet'					: 'Your planet',
		'ov_coords'							: 'Position',
		'ov_abandon_planet'					: 'abandon colony',
		'ov_planet_name'					: 'Name',
		'ov_actions'						: 'Functions',
		'ov_planet_rename'					: 'rename',
		'ov_planet_rename_action'			: 'rename',
		'ov_abandon_planet_not_possible'	: 'It\'s not possible abandon a planet where are fleets moving',
		'ov_fields'							: 'Fields',
		
		
		'gl_no_deuterium_to_view_galaxy'	: 'You don\'t have enough deuterium!',
		'gl_legend'							: 'Legend',
		'gl_strong_player'					: 'stronger player',
		'gl_week_player'					: 'weaker player (newbie)',
		'gl_vacation'						: 'Vacation Mode',
		'gl_banned'							: 'banned',
		'gl_inactive_seven'					: '7 days inactive',
		'gl_inactive_twentyeight'			: '28 days inactive',
		'gl_s'								: 's',
		'gl_w'								: 'n',
		'gl_v'								: 'v',
		'gl_b'								: 'b',
		'gl_i'								: 'i',
		'gl_I'								: 'I',
		'gl_populed_planets'				: 'planets colonized',
		'gl_out_space'						: 'Outer Space',
		'gl_avaible_missiles'				: 'missiles available',
		'gl_fleets'							: 'fleets',
		'gl_avaible_recyclers'				: 'recyclers available',
		'gl_avaible_spyprobes'				: 'probes available',
		'gl_missil_launch'					: 'Missile Launch',
		'gl_missil_to_launch'				: 'Number of missiles (<b>%d</b> left):',
		'gl_all_defenses'					: 'All',
		'gl_objective'						: 'Objective',
		'gl_missil_launch_action'			: 'OK',
		'gl_galaxy'							: 'Galaxy',
		'gl_solar_system'					: 'System',
		'gl_show'							: 'Display',
		'gl_pos'							: 'Slot',
		'gl_planet'							: 'Planet',
		'gl_name_activity'					: 'Name (activity)',
		'gl_moon'							: 'Moon',
		'gl_debris'							: 'DF',
		'gl_player_estate'					: 'Player (status)',
		'gl_alliance'						: 'Alliance',
		'gl_actions'						: 'Actions',
		'gl_spy'							: 'Espionage',
		'gl_buddy_request'					: 'Buddy request',
		'gl_missile_attack'					: 'Missile attack',
		'gl_with'							: ' consisting of ',
		'gl_member'							: ' member',
		'gl_member_add'						: '(s)',
		'gl_alliance_page'					: 'Alliance Page',
		'gl_see_on_stats'					: 'Statistics',
		'gl_alliance_web_page'				: 'Alliance Homepage',
		'gl_debris_field'					: 'Debris field',
		'gl_collect'						: 'Harvest',
		'gl_resources'						: 'Resources',
		'gl_features'						: 'Features',
		'gl_diameter'						: 'Diameter',
		'gl_temperature'					: 'Temperature',
		'gl_phalanx'						: 'Phalanx',
		'gl_planet_destroyed'				: 'Planet destroyed',
		'gl_player'							: '',
		'gl_in_the_rank'					: ' ranked ',
		'gl_stat'							: 'Statistics',
		
		
		'px_no_deuterium'					: 'You don\'t have enough deuterium!',
		'px_scan_position'					: 'Scan position',
		'px_fleet_movement'					: 'Current Fleet Movement',
		
		
		'iv_imperium_title'					: 'Empire vision',
		'iv_planet'							: 'Planet',
		'iv_name'							: 'Name',
		'iv_coords'							: 'Coords',
		'iv_fields'							: 'Fields',
		'iv_resources'						: 'Resources',
		'iv_buildings'						: 'Buildings',
		'iv_technology'						: 'Technologies',
		'iv_ships'							: 'Ships',
		
		'iv_defenses'						: 'Defenses',
		
		
		'fl_returning'						: 'Returning',
		'fl_onway'							: 'On the road',
		'fl_r'								: '(R)',
		'fl_a'								: '(A)',
		'fl_send_back'						: 'Back',
		'fl_acs'							: 'ACS',
		'fl_no_more_slots'					: 'All fleet slots are being used',
		'fl_speed_title'					: 'Speed: ',
		'fl_continue'						: 'continue',
		'fl_no_ships'						: 'There are no available ships',
		'fl_remove_all_ships'				: 'no ships',
		'fl_select_all_ships'				: 'all ships',
		'fl_fleets'							: 'Fleets',
		'fl_expeditions'					: 'Expeditions',
		'fl_number'							: 'ID',
		'fl_mission'						: 'Mission',
		'fl_ammount'						: 'Ships (total)',
		'fl_beginning'						: 'Beginning',
		'fl_departure'						: 'Departure',
		'fl_destiny'						: 'Destination',
		'fl_objective'						: 'Objective',
		'fl_arrival'						: 'Arrival',
		'fl_order'							: 'Order',
		'fl_new_mission_title'				: 'Please select your ships for this mission:',
		'fl_ship_type'						: 'Ship Type',
		'fl_ship_available'					: 'Available',
		'fl_planet'							: 'Planet',
		'fl_debris'							: 'Debris',
		'fl_moon'							: 'Moon',
		'fl_planet_shortcut'				: '(P)',
		'fl_debris_shortcut'				: '(D)',
		'fl_moon_shortcut'					: '(M)',
		'fl_no_shortcuts'					: 'No shortcuts',
		'fl_anonymous'						: 'Anonymous',
		'fl_shortcut_add_title'				: 'Name Galaxy / System / Planet',
		'fl_shortcut_name'					: 'Name',
		'fl_shortcut_galaxy'				: 'Galaxy',
		'fl_shortcut_solar_system'			: 'Solar system',
		'fl_clean'							: 'Delete',
		'fl_register_shorcut'				: 'Register',
		'fl_shortcuts'						: 'Shortcuts',
		'fl_reset_shortcut'					: 'Reset',
		'fl_dlte_shortcut'					: 'Delete',
		'fl_back'							: 'Back',
		'fl_shortcut_add'					: 'Add',
		'fl_shortcut_edition'				: 'Edit: ',
		'fl_no_colony'						: 'No colonies',
		'fl_send_fleet'						: 'Send fleet',
		'fl_fleet_speed'					: 'Speed',
		'fl_distance'						: 'Distance',
		'fl_flying_time'					: 'Flying time',
		'fl_fuel_consumption'				: 'Fuel consumption',
		'fl_max_speed'						: 'Max. speed',
		'fl_cargo_capacity'					: 'Cargo capacity',
		'fl_shortcut'						: 'Shortcuts',
		'fl_shortcut_add_edit'				: '(Add / Edit)',
		'fl_my_planets'						: 'My planets',
		'fl_acs_title'						: 'Group attack',
		'fl_hold_time'						: 'Stay time',
		'fl_resources'						: 'Resources',
		'fl_max'							: 'max',
		'fl_resources_left'					: 'Resources left',
		'fl_all_resources'					: 'All resources',
		'fl_expedition_alert_message'		: 'Attention! Expeditions are dangerous missions, you can lose your ships!',
		'fl_vacation_mode_active'			: 'Vacation mode active',
		'fl_expedition_tech_required'		: 'Expedition tech required!',
		'fl_expedition_fleets_limit'		: 'Expedition flying fleets limite reached!',
		'fl_week_player'					: 'The player is very weak!',
		'fl_strong_player'					: 'The player is very strong!',
		'fl_in_vacation_player'				: 'The player is in vacation mode!',
		'fl_no_slots'						: 'No more slots available',
		'fl_empty_transport'				: 'You can not transport 0 resources',
		'fl_planet_populed'					: 'This planet is occupied!',
		'fl_stay_not_on_enemy'				: 'You can not park fleets on the enemy planets!',
		'fl_not_ally_deposit'				: 'No Alliance Depot',
		'fl_deploy_only_your_planets'		: 'You can only deploy fleets in your planets!',
		'fl_no_enought_deuterium'			: 'You have not enough deuterium. Deuterium Consumption: ',
		'fl_no_enought_cargo_capacity'		: 'You do not have enough cargo space! Available:',
		'fl_admins_cannot_be_attacked'		: 'Administrators and moderators of this game can not be attacked.',
		'fl_fleet_sended'					: 'Fleet sent',
		'fl_from'							: 'From',
		'fl_arrival_time'					: 'Arrival time',
		'fl_return_time'					: 'Return time',
		'fl_fleet'							: 'Fleet',
		'fl_player'							: 'The player ',
		'fl_add_to_attack'					: ' was added to the attack.',
		'fl_dont_exist'						: ' was not added to the attack.',
		'fl_acs_invitation_message'			: ' invites you to participate in a ACS.',
		'fl_acs_invitation_title'			: 'Invitation to acs',
		'fl_sac_of_fleet'					: 'ACS fleet',
		'fl_modify_sac_name'				: 'Change the name of the ACS',
		'fl_members_invited'				: 'Members invited',
		'fl_invite_members'					: 'Invite other members',
		'fl_hours'							: 'hour(s)',
		
		'bd_dismantle'						: 'Deconstruct',
		'bd_interrupt'						: 'Interrupt',
		'bd_cancel'							: 'cancel',
		'bd_working'						: 'Working',
		'bd_build'							: 'Build',
		'bd_build_next_level'				: 'upgrade level ',
		'bd_add_to_list'					: 'Add to list',
		'bd_no_more_fields'					: 'No more room on the planet',
		'bd_remaining'						: 'Remaining',
		'bd_lab_required'					: 'You need to build a research laboratory on this planet first!',
		'bd_building_lab'					: 'Can not research when the laboratory is upgrading',
		'bd_lvl'							: 'level',
		'bd_spy'							: ' spy',
		'bd_commander'						: ' commander',
		'bd_research'						: 'research',
		'bd_shipyard_required'				: 'You need to build a shipyard on this planet first!',
		'bd_building_shipyard'				: 'You can not build ships when the shipyard is upgrading',
		'bd_available'						: 'Available: ',
		'bd_build_ships'					: 'Build',
		'bd_protection_shield_only_one'		: 'The shield can be built only once!',
		'bd_build_defenses'					: 'Build',
		'bd_actual_production'				: 'Actual production:',
		'bd_completed'						: 'Completed',
		'bd_operating'						: '(Working)',
		'bd_continue'						: 'continue',
		'bd_ready'							: 'finished',
		'bd_finished'						: 'finished',
		'bd_work_todo'						: 'Construction queue',
		
		'rs_amount'							: 'quantity',
		'rs_lvl'							: 'level',
		'rs_production_on_planet'			: 'Resource production on planet "%s"',
		'rs_basic_income'					: 'Basic Income',
		'rs_storage_capacity'				: 'Storage Capacity',
		'rs_calculate'						: 'calculate',
		'rs_sum'							: 'Total:',
		'rs_daily'							: 'Res per day:',
		'rs_weekly'							: 'Res per week:',
		
		
		'of_title'							: 'Officers',
		'of_recruit'						: 'Recruit',
		'of_active'							: '<strong><font color:"lime">Active</font></strong>',
		'of_inactive'						: '<strong><font color:"red">Inactive</font></strong>',
		'of_points_per_thousand_darkmatter'	: '(1 point for every 1000 of dark matter)',
		'of_lvl'	: 'level',
		'success'	 : "Officer was recruited!",
		'NoPoints'	 : "You do not have enough Dark Matter",
		'Noob' : "Officer do not accessible at this time.",
		'NonExist'	 : "Officer does not exist",
		'days' : "Days",
		'hours' : "Hours",
		'mins' : "Minutes",					
		'activefor' : "Hired for ",
		
		'officier'	 : "Officers",
		
		'off_points'	 : "Dark Matter : ",
		'hireduntil'	 : "Hired for",
		
		'Maxlvl'		 : "You already have this officer.",
		'Officier'	 : "Officer",
		
		"commander_feature" : "This feature is only available for players with commander",
		"not_av" : "Not available",
		
		'title_off_geologist' : "Geologist",
		'title_off_scientist' : "Scientist",
		'title_off_engineer' : "Engineer",
		'title_off_general' : "General",
		'title_off_admiral' : "Admiral",
		'title_off_energy' : "Power Engineer",
		'title_off_storer' : "The Quartermaster",
		'title_off_spy' : "Espionage officer",
		'title_off_exspy' : "Counter espionage officer",
		
		'link_1'   : "Hire for 3 days",
		'link_2'   : "Hire for 1 week",
		
		'link_off_geologist' : "Hire Geologist",
		'link_off_scientist' : "Hire Scientist",
		'link_off_engineer' : "Hire Engineer",
		'link_off_general' : "Hire General",
		'link_off_admiral' : "Hire Admiral",
		'link_off_energy' : "Hire Power Engineer",
		
		
		'tr_only_positive_numbers'			: 'You may only use positive numbers!',
		'tr_not_enought_metal'				: 'You do not have enough metal.',
		'tr_not_enought_crystal'				: 'You do not have enough crystal.',
		'tr_not_enought_deuterium'			: 'You do not have enough deuterium.',
		'tr_exchange_done'					: 'Exchange successful',
		'tr_call_trader'						: 'Call a dealer',
		'tr_call_trader_who_buys'			: 'Call a dealer who buy ',
		'tr_call_trader_submit'				: 'Call trader',
		'tr_exchange_quota'					: 'The exchange rate is 2/1/0.5',
		'tr_sell_metal'						: 'Sales of metal',
		'tr_sell_crystal'					: 'Sales of crystal',
		'tr_sell_deuterium'					: 'Sales of deuterium',
		'tr_resource'						: 'Resource',
		'tr_amount'							: 'Quantity',
		'tr_quota_exchange'					: 'Exchange rate',
		'tr_exchange'						: 'Swap',
		'tr_darkmatter_needed'				: 'You need at least <font color:"#FF8900">%s of dark matter</font> too visit the dealer.',
		'tr_full_storage'					: 'The %s is full',
		
		
		'tt_requirements'					: 'Requirements',
		'tt_lvl'								: 'level ',
		
		
		'tech_buildings' : "Buildings",
		'tech_metal_mine' : "Metal Mine",
		'tech_crystal_mine' : "Crystal Mine",
		'tech_deuterium_synthesizer' : "Deuterium Synthesizer",
		'tech_solar_plant' : "Solar Plant",
		'tech_fusion_reactor' : "Fusion Reactor",
		'tech_robotics_factory' : "Robotics Factory",
		'tech_nanite_factory' : "Nanite Factory",
		'tech_shipyard' : "Shipyard",
		'tech_metal_storage' : "Metal Storage",
		'tech_crystal_storage' : "Crystal Storage",
		'tech_deuterium_storage' : "Deuterium Tank",
		'tech_research_lab' : "Research Lab",
		'tech_terraformer' : "Terraformer",
		'tech_luna' : "Lunar Buildings",
		'tech_moon_base' : "Lunar Base",
		'tech_sensor_phalanx' : "Sensor Phalanx",
		'tech_jump_gate' : "Jump Gate",
		'tech_missile_silo' : "Missile Silo",
		
		'tech_research' : "Research",
		'tech_espionage_tech' : "Espionage Technology",
		'tech_computer_tech' : "Computer Technology",
		'tech_weapons_tech' : "Weapons Technology",
		'tech_shielding_tech' : "Shielding Technology",
		'tech_armour_tech' : "Armour Technology",
		'tech_energy_tech' : "Energy Technology",
		'tech_hyperspace_tech' : "Hyperspace Technology",
		'tech_combustion_drive_tech' : "Combustion Drive",
		'tech_impulse_drive_tech' : "Impulse Drive",
		'tech_hyperspace_drive_tech' : "Hyperspace Drive",
		'tech_laser_tech' : "Laser Technology",
		'tech_ion_tech' : "Ion Technology",
		'tech_plasma_tech' : "Plasma Technology",
		'tech_intergalactic_research_tech' : "Intergalactic Research Network",
		'tech_astrophysics_tech' : "Astrophysics",
		'tech_graviton_tech' : "Graviton Technology",
		
		'tech_ships' : "Ships",
		'tech_small_cargo' : "Small Cargo",
		'tech_large_cargo' : "Large Cargo",
		'tech_light_fighter' : "Light Fighter",
		'tech_heavy_fighter' : "Heavy Fighter",
		'tech_cruiser' : "Cruiser",
		'tech_battleship' : "Battleship",
		'tech_colony_ship' : "Colony Ship",
		'tech_recycler' : "Recycler",
		'tech_espionage_probe' : "Espionage Probe",
		'tech_bomber' : "Bomber",
		'tech_solar_satellite' : "Solar Satellite",
		'tech_destroyer' : "Destroyer",
		'tech_deathstar' : "Deathstar",
		'tech_battlecruiser' : "Battlecruiser",
		'tech_ufo' : "UFO",
		
		'tech_defense' : "Defense",
		'tech_rocket_launcher' : "Rocket Launcher",
		'tech_light_laser' : "Light Laser",
		'tech_heavy_laser' : "Heavy Laser",
		'tech_gauss_cannon' : "Gauss Cannon",
		'tech_ion_cannon' : "Ion Cannon",
		'tech_plasma_cannon' : "Plasma Turret",
		'tech_small_shield_dome' : "Small Shield Dome",
		'tech_large_shield_dome' : "Large Shield Dome",
		'tech_anti_ballistic_missiles' : "Anti-Ballistic Missiles",
		'tech_interplanetary_missiles' : "Interplanetary Missiles",
		
		
		'res_descriptions_metal_mine' : "Produces metal, the main constituent of buildings, ships and defenses.",
		'res_descriptions_crystal_mine' : "Produces Crystal, a major component of many technological researches, ships, defenses and buildings.",
		'res_descriptions_deuterium_synthesizer' : "Extracts small quantities of deuterium from under the planets surface.",
		'res_descriptions_solar_plant' : "The solar power plants convert heat and light energy into electrical energy. All productive buildings need energy to work.",
		'res_descriptions_fusion_reactor' : "The fusion power plant produces energy by fusing 2 hydrogen atoms into a single helium atom.",
		'res_descriptions_robotics_factory' : "The Factory produces robotic workers who increase the speed of building construction and allow production of the shipyard.",
		'res_descriptions_nanite_factory' : "The nanite factory increases production speed on ships, defenses and structures by x2 per level.",
		'res_descriptions_shipyard' : "Provides space to build aggressive ships and defensive structures.",
		'res_descriptions_metal_storage' : "Increased storage space for metal.",
		'res_descriptions_crystal_storage' : "Increased storage space for crystal.",
		'res_descriptions_deuterium_storage' : "Provides a larger tank to store more deuterium.",
		'res_descriptions_research_lab' : "Allows new technologies to be researched and increases speed of current researchable technologies.",
		'res_descriptions_terraformer' : "Teraforms uninhabitable regions of the planet providing more fields for development",
		'res_descriptions_moon_base' : "Allows construction on moons increasing fields.",
		'res_descriptions_sensor_phalanx' : "Using many sensors foreign ship movements can be mapped. this gives information on moving foreign fleets that is otherwise invisible",
		'res_descriptions_jump_gate' : "Instant movement of ships over large distances is only possible with the Jump Gate.",
		'res_descriptions_missile_silo' : "Storage for Antibalistic and Interplanetary missiles.",
		
		'res_descriptions_espionage_tech' : "This technology provides information on other planets in the universe.",
		'res_descriptions_computer_tech' : "With the increased capacity of computers, more fleets can be launched at any time. Each level of computer technology increases the total number of fleet slots by one.",
		'res_descriptions_weapons_tech' : "The weapons technology makes weapons systems more effective. Each level of weapons technology increases the power of weapons of units by 10% of the value base.",
		'res_descriptions_shielding_tech' : "Each level increases shield strength by 10%",
		'res_descriptions_armour_tech' : "Each level increases ship armour by 10%",
		'res_descriptions_energy_tech' : "Advances in energy technology is required for many other technological advances and buildings.",
		'res_descriptions_hyperspace_tech' : "The integration of the 4th and 5th dimension allows the development of a new type of engine it is the most powerful engine available.",
		'res_descriptions_combustion_drive_tech' : "The development of these engines makes vessels faster, but each level increases the speed by 10%.",
		'res_descriptions_impulse_drive_tech' : "Impulse engines power is greater than that of combustion engines, each level increases speed by 20%",
		'res_descriptions_hyperspace_drive_tech' : "Employing spatial and temporal distortion in the engine, space is compressed which allows travel long distances in a short space of time.",
		'res_descriptions_laser_tech' : "The concentration of light creates a beam which causes significant damage when touching an object.",
		'res_descriptions_ion_tech' : "Causing heavy impact damage, Accelerating ions proves a very effective method of attack .",
		'res_descriptions_plasma_tech' : "Plasma causes huge damage to objects it hits, This is required for the very largest defensive structures.",
		'res_descriptions_intergalactic_research_tech' : "Scientists on multiple planets can use this technology to collaborate research decreasing research time.",
		'res_descriptions_astrophysics_tech' : "Astrophysics can be used to further colonize the galaxies. For every two levels of this technology an additional planet can be utilized.",
		'res_descriptions_graviton_tech' : "A network of gravity producing objects can be used to destroy ships, defenses and even moons.",
		
		'res_descriptions_small_cargo' : "The small cargo is an agile ship which can quickly transport resources to other planets.",
		'res_descriptions_large_cargo' : "This cargo ship has a much larger cargo capacity than the small cargo, and is generally faster thanks to an improved drive.",
		'res_descriptions_light_fighter' : "This is the first fighting ship all emperors will build. The light fighter is an agile ship, but vulnerable by themselves. In mass numbers, they can become a great threat to any empire. They are the first to accompany small and large cargo to hostile planets with minor defenses.",
		'res_descriptions_heavy_fighter' : "This fighter is better armoured and has a higher attack strength than the light fighter..",
		'res_descriptions_cruiser' : "Cruisers are armoured almost three times as heavily as heavy fighters and have more than twice the firepower. In addition, they are very fast.",
		'res_descriptions_battleship' : "Battleships form the backbone of a fleet. Their heavy cannons, high speed, and large cargo holds make them opponents to be taken seriously.",
		'res_descriptions_colony_ship' : "Vacant planets can be colonized with this ship.",
		'res_descriptions_recycler' : "Recyclers are the only ships able to harvest debris fields floating in a planets orbit after combat.",
		'res_descriptions_espionage_probe' : "Espionage probes are small, agile drones that provide data on fleets and planets over great distances.",
		'res_descriptions_bomber' : "The bomber was developed especially to destroy the planetary defenses of a world.",
		'res_descriptions_solar_satellite' : "Solar satellites are simple platforms of solar cells, located in a high, stationary orbit. They gather sunlight and transmit it to the ground station via laser.",
		'res_descriptions_destroyer' : "The destroyer is the king of the warships.",
		'res_descriptions_deathstar' : "The destructive power of the deathstar is unsurpassed.",
		'res_descriptions_battlecruiser' : "The Battlecruiser is highly specialized in the interception of hostile fleets.",
		'res_descriptions_ufo' : "Unknown ship.",
		
		'res_descriptions_rocket_launcher' : "The rocket launcher is a simple, cost-effective defensive option.",
		'res_descriptions_light_laser' : "Concentrated firing at a target with photons can produce significantly greater damage than standard ballistic weapons.",
		'res_descriptions_heavy_laser' : "The heavy laser is the logical development of the light laser.",
		'res_descriptions_gauss_cannon' : "The Gauss Cannon fires projectiles weighing tons at high speeds.",
		'res_descriptions_ion_cannon' : "The Ion Cannon fires a continuous beam of accelerating ions, causing considerable damage to objects it strikes.",
		'res_descriptions_plasma_cannon' : "Plasma Turrets release the energy of a solar flare and surpass even the destroyer in destructive effect.",
		'res_descriptions_small_shield_dome' : "The small shield dome covers an entire planet with a field which can absorb a tremendous amount of energy.",
		'res_descriptions_large_shield_dome' : "The development of the large shield dome can employ significantly more energy to withstand attacks.",
		'res_descriptions_anti_ballistic_missiles' : "Anti-Ballistic Missiles destroy attacking interplanetary missiles",
		'res_descriptions_interplanetary_missiles' : "Interplanetary Missiles destroy enemy defenses.",
		
		
		'res_descriptions_off_geologist' : "The Geologist is an expert in mineralogy and crystallography. Utilizing state of the art equipment for surveying, the Geologist can locate optimal areas for mining, increasing mining production by %VAL1%%<font color=red>*</font> on all planets.<br /><font color=green>+%VAL2%% Mine Production*</font><br/><small>*Click on officer icon to get more info.</small>",
		'res_descriptions_off_scientist' : "The Scientist is the foremost authority on research and development. With a natural genius for math and physics the Scientist is able to reduce research times by %VAL1%%.<br /><font color=green>+%VAL2%% Research Speed</font>",
		'res_descriptions_off_engineer' : "The Engineer specializes in governing energy needs and construction plans. Organizing mass scale construction the Engineer is capable of speeding up the production of buildings, ships and defenses by %VAL1%% on all planets.<br /><font color=green>+%VAL2%% Construction Speed (Buildings/Ships/Defenses)</font>",
		'res_descriptions_off_general' : "The General is the pinnacle of the command structure. Leading by example and adhering to a strict code the General is able to inspire great morale in troops, an icon of the military empire the General provides a %VAL1%% bonus to Weapons, Shields and Armor technology. <br /><font color=green>+%VAL2%% Weapons/Shields/Armor</font>",
		'res_descriptions_off_admiral' : "The Admiral is an experienced combat veteran skilled in tactical maneuvering. Through strategic management the Admiral grants an increase to all fleet speeds by %VAL1%%. The Admiral is also an expert at organizing large combat groups allowing for an additional 2 fleet slots.<br /><font color=green>+2 Fleet Slots and +%VAL2%% Ship Speed</font>",
		'res_descriptions_off_energy' : "The Power Engineer is a specialist in energy management. In peacetime, it increases the energy of all the colonies. In case of attack, ensuring the supply of energy to the cannons, and avoid a possible overload, leading to a reduction in defense lost battle.<br><font color=green>+10% of energy production</font>",
		'res_descriptions_off_storer' : "The quartermaster is the epitome of efficiency and logistics. Using the latest in logistic and computational density research the Quartermaster is able to boost storage efficiency across all storage depots on your planets by 20%.<br><font color=green>+20% storage on all planets</font>",
		'res_descriptions_off_spy' : "The Espionage officer is an expert at persuasion, blackmail, and intelligence gathering. Using these skills along with their vast connections in the underground and black markets, the espionage officer is able to boost intelligence gathering on all spy missions.<br><font color=green>+2 espionage technology</font>",
		'res_descriptions_off_exspy' : "The Counter-Espionage officer is the uncorruptible detective of all things destabilizing and subversive. With unique skills in codebreaking and untangling lies. The counter-espionage agent is able to corrupt the data on incoming spy missions.<br><font color=green>-2 espionage technology to anyone who spies on you.</font>",
		
		
		'in_jump_gate_done'					: 'The jump gate was used, the next jump can be made in: ',
		'in_jump_gate_error_data'			: 'Error, data for the jump are not correct!',
		'in_jump_gate_not_ready_target'		: 'The jump gate is not ready on the finish moon, will be ready in ',
		'in_jump_gate_doesnt_have_one'		: 'You have no jump gate in the moon!',
		'in_jump_gate_already_used'			: 'The jump gate was used, time to recharge its energy: ',
		'in_jump_gate_available'				: 'available',
		'in_rf_again'    					: 'Rapidfire against',
		'in_rf_from'     					: 'Rapidfire from',
		'in_level'       					: 'Level',
		'in_prod_p_hour' 					: 'Per hour',
		'in_difference'  					: 'Difference',
		'in_used_energy' 					: 'Energy consumption',
		'in_prod_energy' 					: 'Energy Production',
		'in_used_deuter'						: 'Deuterium consumption',
		'in_range'       					: 'Sensor range',
		'in_title_head'  					: 'Information of',
		'in_name'        					: 'Name',
		'in_struct_pt'   					: 'Structural Integrity',
		'in_shield_pt'   					: 'Shield Strength',
		'in_attack_pt'   					: 'Attack Strength',
		'in_capacity'    					: 'Cargo Capacity',
		'in_units'       					: 'units',
		'in_base_speed' 						: 'Base speed',
		'in_consumption' 					: 'Fuel usage (Deuterium)',
		'in_jump_gate_start_moon'			: 'Start moon',
		'in_jump_gate_finish_moon'			: 'Finish moon',
		'in_jump_gate_select_ships'			: 'Use Jump Gate: number of ships',
		'in_jump_gate_jump'					: 'Jump',
		'in_destroy'     					: 'Destroy:',
		'in_needed'      					: 'Requires',
		'in_dest_durati' 					: 'Destruction time',
		
		'info_metal_mine_name'          			: "Metal Mine",
		'info_metal_mine_description'   			: "Metal is the primary resource used in the foundation of your Empire. At greater depths, the mines can produce more output of viable metal for use in the construction of buildings, ships, defense systems, and research. As the mines drill deeper, more energy is required for maximum production. As metal is the most abundant of all resources available, its value is considered to be the lowest of all resources for trading.",
		'info_crystal_mine_name'          			: "Crystal Mine",
		'info_crystal_mine_description'   			: "Crystals are the main resource used to build electronic circuits for computers and other electronic circuits and form certain alloy compounds for shields. Compared to the metal production process, the processing of raw crystalline structures into industrial crystals requires special processing. As such, more energy is required to process the raw crystal than needed for metal. Development of ships and buildings, and specialized research upgrades, require a certain quantity of crystals.",
		'info_deuterium_synthesizer_name'          			: "Deuterium Synthesizer",
		'info_deuterium_synthesizer_description'   			: "Deuterium is also called heavy hydrogen. It is a stable isotope of hydrogen with a natural abundance in the oceans of colonies of approximately one atom in 6500 of hydrogen (~154 PPM). Deuterium thus accounts for approximately 0.015% (on a weight basis, 0.030%) of all. Deuterium is processed by special synthesizers which can separate the water from the Deuterium using specially designed centrifuges. The upgrade of the synthesizer allows for increasing the amount of Deuterium deposits processed. Deuterium is used when carrying out sensor phalanx scans, viewing galaxies, as fuel for ships, and performing specialized research upgrades.",
		
		'info_solar_plant_name'          			: "Solar Plant",
		'info_solar_plant_description'   			: "Gigantic solar arrays are used to generate power for the mines and the deuterium synthesizer. As the solar plant is upgraded, the surface area of the photovoltaic cells covering the planet increases, resulting in a higher energy output across the power grids of your planet.",
		'info_fusion_reactor_name'         			: "Fusion Reactor",
		'info_fusion_reactor_description'  			: "In fusion power plants, hydrogen nuclei are fused into helium nuclei under enormous temperature and pressure, releasing tremendous amounts of energy. For each gram of Deuterium consumed, up to 41,32*10^-13 Joule of energy can be produced, with 1 g you are able to produce 172 MWh energy.<br><br>Larger reactor complexes use more deuterium and can produce more energy per hour. The energy effect could be increased by researching energy technology.<br><br>The energy production of the fusion plant is calculated like that:<br>30 * Level Fusion Plant * (1,05 + Level Energy Technology * 0,01) ^ Level Fusion Plant",
		
		'info_robotics_factory_name'         			: "Robotics Factory",
		'info_robotics_factory_description'  			: "The Robotics Factory primary goal is the production of State of the Art construction robots. Each upgrade to the robotics factory results in the production of faster robots, which is used to reduce the time needed to construct buildings.",
		'info_nanite_factory_name'         			: "Nanite Factory",
		'info_nanite_factory_description'  			: "A nanomachine, also called a nanite, is a mechanical or electromechanical device whose dimensions are measured in nanometers (millionths of a millimeter, or units of 10^-9 meter). The microscopic size of nanomachines translates into higher operational speed. This factory produces nanomachines that are the ultimate evolution in robotics technology. Once constructed, each upgrade significantly decreases production time for buildings, ships, and defensive structures.",
		'info_shipyard_name'         			: "Shipyard",
		'info_shipyard_description'  			: "The planetary shipyard is responsible for the construction of spacecraft and defensive mechanisms. As the shipyard is upgraded, it can produce a wider variety of vehicles at a much greater rate of speed. If a nanite factory is present on the planet, the speed at which ships are constructed is massively increased.",
		'info_metal_storage_name'         			: "Metal Storage",
		'info_metal_storage_description'  			: "This storage facility is used to store metal ore. Each level of upgrading increases the amount of metal ore that can be stored. If the storage capacity is exceeded, the metal mines are automatically shut down to prevent a catastrophic collapse in the metal mine shafts.",
		'info_crystal_storage_name'         			: "Crystal Storage",
		'info_crystal_storage_description'  			: "Raw crystal is stored in this building. With each level of upgrade, it increases the amount of crystal can be stored. Once the mines output exceeds the storage capacity, the crystal mines automatically shut down to prevent a collapse in the mines.",
		'info_deuterium_storage_name'         			: "Deuterium Tank",
		'info_deuterium_storage_description'  			: "The Deuterium tank is for storing newly-synthesized deuterium. Once it is processed by the synthesizer, it is piped into this tank for later use. With each upgrade of the tank, the total storage capacity is increased. Once the capacity is reached, the Deuterium Synthesizer is shut down to prevent the tanks rupture.",
		'info_research_lab_name'         			: "Research Lab",
		'info_research_lab_description'  			: "An essential part of any empire, Research Labs are where new technologies are discovered, and older technologies are improved upon. With each level of the Research Lab constructed, the speed in which new technologies are researched is increased, while also unlocking newer technologies to research. In order to conduct research as quickly as possible, research scientists are immediately dispatched to the colony to begin work and development. In this way, knowledge about new technologies can easily be disseminated throughout the empire.",
		'info_terraformer_name'         			: "Terraformer",
		'info_terraformer_description'  			: "With the ever increasing mining of a colony, a problem arose. How can we continue to operate at a planets capacity and still survive? The land is being mined out and the atmosphere is deteriorating. Mining a colony to capacity can not only destroy the planet, but may kill all life on it. Scientists working feverishly discovered a method of creating enormous land masses using nanomachines. The Terraformer was born.<br><br>Once built, the Terraformer cannot be torn down.",
		'info_moon_base_name'         			: "Lunar Base",
		'info_moon_base_description'  			: "Since a moon has no atmosphere and is an extremely hostile environment, a lunar base must first be built before the moon can be developed. The Lunar Base provides oxygen, heating, and gravity to create a living environment for the colonists. With each level constructed, a larger living and development area is provided within the biosphere. With each level of the Lunar Base constructed, three fields are developed for other buildings. <br>Once built, the lunar base can not be torn down.",
		'info_sensor_phalanx_name'         			: "Sensor Phalanx",
		'info_sensor_phalanx_description'  			: "Utilizing high-resolution sensors, the Sensor Phalanx first scans the spectrum of light, composition of gases, and radiation emissions from a distant world and transmits the data to a supercomputer for processing. Once the information is obtained, the supercomputer compares changes in the spectrum, gas composition, and radiation emissions, to a base line chart of known changes of the spectrum created by various ship movements. The resulting data then displays activity of any fleet within the range of the phalanx. To prevent the supercomputer from overheating during the process, it is cooled by utilizing 5k of processed Deuterium. To use the Phalanx, click on any planet in the Galaxy View within your sensors range.",
		'info_jump_gate_name'         			: "Jump Gate",
		'info_jump_gate_description'  			: "A Jump Gate is a system of giant transceivers capable of sending even the largest fleets to a receiving Gate anywhere in the universe without loss of time. Utilizing technology similar to that of a Worm Hole to achieve the jump, deuterium is not required. A recharge period of one hour must pass between jumps to allow for regeneration. Transporting resources through the Gate is not possible.",
		'info_missile_silo_name'         			: "Missile Silo",
		'info_missile_silo_description'  			: "When Earth destroyed itself in a full scale nuclear exchange back in the 21st century, the technology needed to build such weapons still existed in the universe. Scientists all over the universe worried about the threat of a nuclear bombardment from a rogue leader. So it was decided to use the same technology as a deterrent from launching such a horrible attack.<br><br> Missile silos are used to construct, store and launch interplanetary and anti-ballistic missiles. With each level of the silo, five interplanetary missiles or ten anti-ballistic missiles can be stored. Storage of both Interplanetary missiles and Anti-Ballistic missiles in the same silo is allowed.",
		
		'info_espionage_tech_name'        			: "Espionage Technology",
		'info_espionage_tech_description' 			: 'Espionage Technology is your intelligence gathering tool. This technology allows you to view your targets resources, fleets, buildings, and research levels using specially designed probes. Launched on your target, these probes transmit back to your planet an encrypted data file that is fed into a computer for processing. After processing, the information on your target is then displayed for evaluation.<br><br> With Espionage Technology, the level of your technology to that of your target is critical. If your target has a higher level of Espionage Technology than you, you will need to launch more probes to gather all the information on your target. However this runs the great risk of detection by your target, resulting in the probes destruction. However, launching too few probes will result in missing information that is most critical, which could result in the total destruction of your fleet if an attack is launched.<br><br>At certain levels of Espionage Technology research, new attack warning systems are installed:<br><br>At Level <font color:"#ff0000">2</font>, the total number of attacking ships will be displayed along with the simple attack warning.<br>At Level <font color:"#ff0000">4</font>, the type of attacking ships along with the number of ships are displayed.<br>At Level <font color:"#ff0000">8</font>, the exact number of each type of ship launched is displayed.',
		'info_computer_tech_name'        			: "Computer Technology",
		'info_computer_tech_description' 			: "Once launched on any mission, fleets are controlled primarily by a series of computers located on the originating planet. These massive computers calculate the exact time of arrival, controls course corrections as needed, calculates trajectories, and regulates flight speeds. <br><br>With each level researched, the flight computer is upgraded to allow an additional slot to be launched. Computer technology should be continuously developed throughout the building of your empire.",
		'info_weapons_tech_name'        			: "Weapons Technology",
		'info_weapons_tech_description' 			: "Weapons Technology is a key research technology and is critical to your survival against enemy Empires. With each level of Weapons Technology researched, the weapons systems on ships and your defense mechanisms become increasingly more efficient. Each level increases the base strength of your weapons by 10% of the base value.",
		'info_shielding_tech_name'        			: "Shielding Technology",
		'info_shielding_tech_description' 			: "With the invention of the magnetosphere generator, scientists learned that an artificial shield could be produced to protect the crew in space ships not only from the harsh solar radiation environment in deep space, but also provide protection from enemy fire during an attack. Once scientists finally perfected the technology, a magnetosphere generator was installed on all ships and defence systems. <br><br>As the technology is advanced to each level, the magnetosphere generator is upgraded which provides an additional 10% strength to the shields base value.",
		'info_armour_tech_name'        			: "Armour Technology",
		'info_armour_tech_description' 			: "The environment of deep space is harsh. Pilots and crew on various missions not only faced intense solar radiation, they also faced the prospect of being hit by space debris, or destroyed by enemy fire in an attack. With the discovery of an aluminum-lithium titanium carbide alloy, which was found to be both light weight and durable, this afforded the crew a certain degree of protection. With each level of Armour Technology developed, a higher quality alloy is produced, which increases the armours strength by 10%.",
		'info_energy_tech_name'        			: "Energy Technology",
		'info_energy_tech_description' 			: "As various researches were advancing, it was discovered that the current technology of energy distribution was not sufficient enough to begin certain specialized researches. With each upgrade of your Energy Technology, new researches can be conducted which unlocks development of more sophisticated ships and defenses.",
		'info_hyperspace_tech_name'        			: "Hyperspace Technology",
		'info_hyperspace_tech_description' 			: 'In theory, the idea of hyperspace travel relies on the existence of a separate and adjacent dimension. When activated, a hyperspace drive shunts the starship into this other dimension, where it can cover vast distances in an amount of time greatly reduced from the time it would take in "normal" space. Once it reaches the point in hyperspace that corresponds to its destination in real space, it re-emerges.<br> Once a sufficient level of Hyperspace Technology is researched, the Hyperspace Drive is no longer just a theory.',
		'info_combustion_drive_tech_name'        			: "Combustion Drive",
		'info_combustion_drive_tech_description' 			: "The Combustion Drive is the oldest of technologies, but is still in use. With the Combustion Drive, exhaust is formed from propellants carried within the ship prior to use. In a closed chamber, the pressures are equal in each direction and no acceleration occurs. If an opening is provided at the bottom of the chamber then the pressure is no longer opposed on that side. The remaining pressure gives a resultant thrust in the side opposite the opening, which propels the ship forward by expelling the exhaust rearwards at extreme high speed.<br> <br>With each level of the Combustion Drive developed, the speed of small and large cargo ships, light fighters, recyclers, and espionage probes are increased by 10%.",
		'info_impulse_drive_tech_name'        			: "Impulse Drive",
		'info_impulse_drive_tech_description' 			: 'The impulse drive is essentially an augmented fusion rocket, usually consisting of a fusion reactor,an accelerator-generator, a driver coil assembly and a vectored thrust nozzle to direct the plasma exhaust. The fusion reaction generates a highly energized plasma. This plasma, ("electro-plasma") can be employed for propulsion, or can be diverted through the EPS to the power transfer grid, via EPS conduits, so as to supply other systems. The accelerated plasma is passed through the driver coils, thereby generating a subspace field which improves the propulsive effect. <br><br>With each level of the Impulse Drive developed, the speed of bombers, cruisers, heavy fighters, and colony ships are increased by 20% of the base value. Interplanetary missiles also travel farther with each level.',
		'info_hyperspace_drive_tech_name'        			: "Hyperspace Drive",
		'info_hyperspace_drive_tech_description' 			: "With the advancement of Hyperspace Technology, the Hyperspace Drive was created. Hyperspace is an alternate region of space co-existing with our own universe which may be entered using an energy field or other device. The HyperSpace Drive utilizes this alternate region by distorting the space-time continuum, which results in speeds that exceed the speed of light (otherwise known as FTL travel). During FTL travel, time and space is warped to the point that results in a trip that would normally take 1000 light years to be completed, to be accomplished in about an hour. <br><br>With each level the Hyperspace Drive is developed, the speed of battleships, battlecruisers, destroyers, and deathstars are increased by 30%.",
		'info_laser_tech_name'        			: "Laser Technology",
		'info_laser_tech_description' 			: "In physics, a laser is a device that emits light through a specific mechanism for which the term laser is an acronym: Light Amplification by Stimulated Emission of Radiation. Lasers have many uses to the empire, from upgrading computer communications systems to the creation of newer weapons and space ships.",
		'info_ion_tech_name'        			: "Ion Technology",
		'info_ion_tech_description' 			: "Simply put, an ion is an atom or a group of atoms that has acquired a net electric charge by gaining or losing one or more electrons. Utilized in advanced weapons systems, a concentrated beam of Ions can cause considerable damage to objects that it strikes.",
		'info_plasma_tech_name'        			: "Plasma Technology",
		'info_plasma_tech_description' 			: "In the universe, there exists four states of matter: solid, liquids, gas, and plasma. Being an advanced version of Ion technology, Plasma Technology expands on the destructive effect that Ion Technology delivered, and opens the door to create advanced weapons systems and ships. Plasma matter is created by superheating gas and compressing it with extreme high pressures to create a sphere of superheated plasma matter. The resulting plasma sphere causes considerable damage to the target in which the sphere is launched to.",
		'info_intergalactic_research_tech_name'        			: "Intergalactic Research Network",
		'info_intergalactic_research_tech_description' 			: "This is your deep space network to communicate researches to your colonies. With the IRN, faster research times can be achieved by linking the highest level research labs equal to the level of the IRN developed. <br><br>In order to function, each colony must be able to conduct the research independently.",
		'info_astrophysics_tech_name'        			: "Astrophysics Technology",
		'info_astrophysics_tech_description' 			: "Astrophysics can be used to further colonize the galaxies. For every two levels of this technology an additional planet can be utilized.",
		'info_graviton_tech_name'        			: "Graviton Technology",
		'info_graviton_tech_description' 			: "The graviton is an elementary particle that mediates the force of gravity in the framework of quantum field theory. The graviton must be massless (because the gravitational force has unlimited range) and must have a spin of 2 (because gravity is a second-rank tensor field). Graviton Technology is only used for one thing, for the construction of the fearsome DeathStar. <br><br>Out of all of the technologies to research, this one carries the most risk of detection during the phase of preparation.",
		
		'info_small_cargo_name'        			: "Small Cargo",
		'info_small_cargo_description' 			: "The first ship built by any emperor, the small cargo is an agile resource moving ship that has a cargo capacity of 5,000 resource units. This multi-use ship not only has the ability to quickly transport resources between your colonies, but also accompanies larger fleets on raiding missions on enemy targets. Ship refitted with Impulse Drives once reached level 5",
		'info_large_cargo_name'        			: "Large Cargo",
		'info_large_cargo_description' 			: "As time evolved, the raids on colonies resulted in larger and larger amounts of resources being captured. As a result, Small Cargos were being sent out in mass numbers to compensate for the larger captures. It was quickly learned that a new class of ship was needed to maximize resources captured in raids, yet also be cost effective. After much development, the Large Cargo was born.<br><br>To maximize the resources that can be stored in the holds, this ship has little in the way of weapons or armor. Thanks to the highly developed combustion engine installed, it serves as the most economical resource supplier between planets, and most effective in raids on hostile worlds.",
		'info_light_fighter_name'        			: "Light Fighter",
		'info_light_fighter_description' 			: "This is the first fighting ship all emperors will build. The light fighter is an agile ship, but vulnerable by themselves. In mass numbers, they can become a great threat to any empire. They are the first to accompany small and large cargo to hostile planets with minor defenses.",
		'info_heavy_fighter_name'        			: "Heavy Fighter",
		'info_heavy_fighter_description' 			: "In developing the heavy fighter, researchers reached a point at which conventional drives no longer provided sufficient performance. In order to move the ship optimally, the impulse drive was used for the first time. This increased the costs, but also opened new possibilities. By using this drive, there was more energy left for weapons and shields, in addition, high-quality materials were used for this new family of fighters. With these changes, the heavy fighter represents a new era in ship technology and is the basis for cruiser technology.<br><br>Slightly larger than the light fighter, the heavy fighter has thicker hulls, providing more protection, and stronger weaponry.",
		'info_cruiser_name'        			: "Cruiser",
		'info_cruiser_description' 			: "With the development of the heavy laser and the ion cannon, light and heavy fighters encountered an alarmingly high number of defeats that increased with each raid. Despite many modifications, weapons strength and armour changes, it could not be increased fast enough to effectively counter these new defensive measures. Therefore, it was decided to build a new class of ship that combined more armor and more firepower. As a result of years of research and development, the Cruiser was born. <br><br>Cruisers are armored almost three times of that of the heavy fighters, and possess more than twice the firepower of any combat ship in existence. They also possess speeds that far surpassed any spacecraft ever made. For almost a century, cruisers dominated the universe. However, with the development of Gauss cannons and plasma turrets, their predominance ended. They are still used today against fighter groups, but not as predominantly as before.",
		'info_battleship_name'        			: "Battleship",
		'info_battleship_description' 			: "Once it became apparent that the cruiser was losing ground to the increasing number of defense structures it was facing, and with the loss of ships on missions at unacceptable levels, it was decided to build a ship that could face those same type of defense structures with as little loss as possible. After extensive development, the Battleship was born. Built to withstand the largest of battles, the Battleship features large cargo spaces, heavy cannons, and high hyperdrive speed. Once developed, it eventually turned out to be the backbone of every raiding Emperors fleet.",
		'info_colony_ship_name'        			: "Colony Ship",
		'info_colony_ship_description' 			: "In the 20th Century, Man decided to go for the stars. First, it was landing on the Moon. After that, a space station was built. Mars was colonized soon afterwards. It was soon determined that our growth depended on colonizing other worlds. Scientists and engineers all over the world gathered together to develop mans greatest achievement ever. The Colony Ship is born.<br><br>This ship is used to prepare a newly discovered planet for colonization. Once it arrives at the destination, the ship is instantly transformed into habital living space to assist in populating and mining the new world. 9 Planets maximum can be colonized.",
		'info_recycler_name'        			: "Recycler",
		'info_recycler_description' 			: "As space battles became larger and more fierce, the resultant debris fields became too large to gather safely by conventional means. Normal transporters could not get close enough without receiving substantial damage. A solution was developed to this problem. The Recycler. <br><br>Thanks to the new shields and specially built equipment to gather wreckage, gathering debris no longer presented a danger. Each Recycler can gather 20,000 units of debris.",
		'info_espionage_probe_name'       			: "Espionage Probe",
		'info_espionage_probe_description' 			: "Espionage probes are small, agile drones that provide data on fleets and planets. Fitted with specially designed engines, it allows them to cover vast distances in only a few minutes. Once in orbit around the target planet, they quickly collect data and transmit the report back via your Deep Space Network for evaluation. But there is a risk to the intelligent gathering aspect. During the time the report is transmitted back to your network, the signal can be detected by the target and the probes can be destroyed.",
		'info_bomber_name'        			: "Bomber",
		'info_bomber_description' 			: "Over the centuries, as defenses were starting to get larger and more sophisticated, fleets were starting to be destroyed at an alarming rate. It was decided that a new ship was needed to break defenses to ensure maximum results. After years of research and development, the Bomber was created.<br><br>Using laser-guided targeting equipment and Plasma Bombs, the Bomber seeks out and destroys any defense mechanism it can find. As soon as the hyperspace drive is developed to Level 8, the Bomber is retrofitted with the hyperspace engine and can fly at higher speeds.",
		'info_solar_satellite_name'        			: "Solar Satellite",
		'info_solar_satellite_description' 			: "It quickly became apparent that more energy was needed to power larger mines then could be produced by conventional ground based solar planets and fusion reactors. Scientists worked on the problem and discovered a method of transmitting electrical energy to the colony using specially designed satellites in geosynchronous orbit.<br><br> Solar Satellites gather solar energy and transmit it to a ground station using advanced laser technology. The efficiency of a solar satellite depends on the strength of the solar radiation it receives. In principle, energy production in orbits closer to the sun is greater than for planets in orbits distant from the sun. Since the satellites primary goal is the transmission of energy, they lack shielding and weapons capability, and because of this they are usually destroyed in large numbers in a major battle. However they do possess a small self-defense mechanism to defend itself in an espionage mission from an enemy empire if the mission is detected.",
		'info_destroyer_name'        			: "Destroyer",
		'info_destroyer_description' 			: "The Destroyer is the result of years of work and development. With the development of Deathstars, it was decided that a class of ship was needed to defend against such a massive weapon.Thanks to its improved homing sensors, multi-phalanx Ion cannons, Gauss Cannons and Plasma Turrets, the Destroyer turned out to be one of the most fearsome ships created.<br><br>Because the destroyer is very large, its maneuverability is severely limited, which makes it more of a battle station than a fighting ship. The lack of maneuverability is made up for by its sheer firepower, but it also costs significant amounts of deuterium to build and operate.",
		'info_deathstar_name'        			: "Deathstar",
		'info_deathstar_description' 			: "The Deathstar is the ultimate ship ever created. This moon sized ship is the only ship that can be seen with the naked eye on the ground. By the time you spot it, unfortunately, it is too late to do anything.<br><br> Armed with a gigantic graviton cannon, the most advanced weapons system ever created in the Universe, this massive ship has not only the capability of destroying entire fleets and defenses, but also has the capability of destroying entire moons. Only the most advanced empires have the capability to build a ship of this mammoth size.",
		'info_battlecruiser_name'        			: "Battlecruiser",
		'info_battlecruiser_description' 			: "This ship is one of the most advanced fighting ships ever to be developed, and is particularly deadly when it comes to destroying attacking fleets. With its improved laser cannons on board and advanced Hyperspace engine, the Battlecruiser is a serious force to be dealt with in any attack.<br><br> Due to the ships design and its large weapons system, the cargo holds had to be cut, but this is compensated for by the lowered fuel consumption.",
		'info_ufo_name'        				: "UFO",
		'info_ufo_description' 				: "Unknown Ship.",
		
		'info_rocket_launcher_name'        			: "Rocket Launcher",
		'info_rocket_launcher_description' 			: "Your first basic line of defense. These are simple ground based launch facilities that fire conventional warhead tipped missiles at attacking enemy targets. As they are cheap to construct and no research is required, they are well suited for defending raids, but lose effectiveness defending from larger scale attacks. Once you begin construction on more advanced defense weapons systems, Rocket Launchers become simple fodder to allow your more damaging weapons to inflict greater damage for a longer period of time.<br><br>After a battle, there is up to a 70 % chance that failed defensive facilities can be returned to use.",
		'info_light_laser_name'        			: "Light Laser",
		'info_light_laser_description' 			: "As technology developed and more sophisticated ships were created, it was determined that a stronger line of defense was needed to counter the attacks. As Laser Technology advanced, a new weapon was designed to provide the next level of defense. Light Lasers are simple ground based weapons that utilize special targeting systems to track the enemy and fire a high intensity laser designed to cut through the hull of the target. In order to be kept cost effective, they were fitted with an improved shielding system, however the structural integrity is the same as that of the Rocket Launcher.<br><br> After a battle, there is up to a 70 % chance that failed defensive facilities can be returned to use.",
		'info_heavy_laser_name'        			: "Heavy Laser",
		'info_heavy_laser_description' 			: "The Heavy Laser is a practical, improved version of the Light Laser. Being more balanced than the Light Laser with improved alloy composition, it utilizes stronger, more densely packed beams, and even better onboard targeting systems. <br><br> After a battle, there is up to a 70 % chance that failed defensive facilities can be returned to use.",
		'info_gauss_cannon_name'        			: "Gauss Cannon",
		'info_gauss_cannon_description' 			: 'Far from being a science-fiction "weapon of tomorrow," the concept of a weapon using an electromagnetic impulse for propulsion originated as far back as the mid-to-late 1930s. Basically, the Gauss Cannon consists of a system of powerful electromagnets which fires a projectile by accelerating between a number of metal rails. Gauss Cannons fire high-density metal projectiles at extremely high velocity. <br><br>This weapon is so powerful when fired that it creates a sonic boom which is heard for miles, and the crew near the weapon must take special precautions due to the massive concussion effects generated.',
		'info_ion_cannon_name'        			: "Ion Cannon",
		'info_ion_cannon_description' 			: "An ion cannon is a weapon that fires beams of ions (positively or negatively charged particles). The Ion Cannon is actually a type of Particle Cannon, only the particles used are ionized. Due to their electrical charges, they also have the potential to disable electronic devices, and anything else that has an electrical or similar power source, using a phenomena known as the the Electromagetic Pulse (EMP effect). Due to the cannons highly improved shielding system, this cannon provides improved protection for your larger, more destructive defense weapons.<br><br> After a battle, there is up to a 70 % chance that failed defensive facilities can be returned to use.",
		'info_plasma_cannon_name'        			: "Plasma Turret",
		'info_plasma_cannon_description' 			: "One of the most advanced defense weapons systems ever developed, the Plasma Turret uses a large nuclear reactor fuel cell to power an electromagnetic accelerator that fires a pulse, or toroid, of plasma. During operation, the Plasma turret first locks on a target and begins the process of firing. A plasma sphere is created in the turrets core by super heating and compressing gases, stripping them of their ions. Once the gas is superheated, compressed, and a plasma sphere is created, it is then loaded into the electromagnetic accelerator which is energized. Once fully energized, the accelerator is activated, which results in the plasma sphere being launched at an extremely high rate of speed to the intended target. From the targets perspective, the approaching bluish ball of plasma is impressive, but once it strikes, it causes instant destruction.<br><br> Defensive facilities deactivate as soon as they are too heavily damaged. After a battle, there is up to a 70 % chance that failed defensive facilities can be returned to use.",
		'info_small_shield_dome_name'        			: "Small Shield Dome",
		'info_small_shield_dome_description' 			: "Colonizing new worlds brought about a new danger, space debris. A large asteroid could easily wipe out the world and all inhabitants. Advancements in shielding technology provided scientists with a way to develop a shield to protect an entire planet not only from space debris but, as it was learned, from an enemy attack. By creating a large electromagnetic field around the planet, space debris that would normally have destroyed the planet was deflected, and attacks from enemy Empires were thwarted. The first generators were large and the shield provided moderate protection, but it was later discovered that small shields did not afford the protection from larger scale attacks. The small shield dome was the prelude to a stronger, more advanced planetary shielding system to come.<br><br> After a battle, there is up to a 70 % chance that failed defensive facilities can be returned to use.",
		'info_large_shield_dome_name'        			: "Large Shield Dome",
		'info_large_shield_dome_description' 			: "The Large Shield Dome is the next step in the advancement of planetary shields, it is the result of years of work improving the Small Shield Dome. Built to withstand a larger barrage of enemy fire by providing a higher energized electromagnetic field, large domes provide a longer period of protection before collapsing.<br><br> After a battle, there is up to a 70 % chance that failed defensive facilities can be returned to use.",
		'info_anti_ballistic_missiles_name'        			: "Anti-Ballistic Missiles",
		'info_anti_ballistic_missiles_description' 			: "Anti Ballistic Missiles (ABM) are your only line of defense when attacked by Interplanetary Missiles (IPM). When a launch of IPMs is detected, these missiles automatically arm, process a launch code in their flight computers, target the inbound IPM, and launch to intercept. During the flight, the target IPM is constantly tracked and course corrections are applied until the ABM reaches the target and destroys the attacking IPM. Each ABM destroys one incoming IPM. <br><br>Each level of your missile silo developed can store 10 ABMs, 5 IPMs, or a combination of both missile types.",
		'info_interplanetary_missiles_name'        			: "Interplanetary Missiles",
		'info_interplanetary_missiles_description' 			: "Interplanetary Missiles (IPM) are your offensive weapon to destroy the defenses of your target. Using state of the art tracking technology, each missile targets a certain number of defenses for destruction. Tipped with an anti-matter bomb, they deliver a destructive force so severe that destroyed shields and defenses cannot be repaired. The only way to counter these missiles is with APMs.<br><br> Each level of your missile silo developed can store 10 ABMs, 5 IPMs, or a combination of both missile types.",
		
		'info_off_geologist_name'        : "Geologist",
		'info_off_geologist_description' : "The Geologist is an expert in mineralogy and crystallography. Utilizing state of the art equipment for surveying, the Geologist can locate optimal areas for mining, increasing mining production on all planets.<br /><be/>Productionby user rank:<br/><font color=red>TOP 50: +10% Mine Production<br/>TOP 51-300: +20% Mine Production<br/>TOP 301-600: +30% Mine Production<br/>TOP 601-1000: +40% Mine Production<br/>TOP 1001-1500: +50% Mine Production<br/>TOP 1501+: +100% Mine Production</font>",
		'info_off_scientist_name'        : "Scientist",
		'info_off_scientist_description' : "The Scientist is the foremost authority on research and development. With a natural genius for math and physics the Scientist is able to reduce research times by 30%.<br /><font color=red>+30% Research Speed</font><br /><font color=red>TOP 50: +10% Research Speed</font>",
		'info_off_engineer_name'        : "Engineer",
		'info_off_engineer_description' : "The Engineer specializes in governing energy needs and construction plans. Organizing mass scale construction the Engineer is capable of speeding up the production of buildings, ships and defenses by 30% on all planets.<br /><font color=red>+30% Construction Speed (Buildings/Ships/Defenses)</font><br/><font color=red>TOP 50: +10% Construction Speed (Buildings/Ships/Defenses)</font>",
		'info_off_general_name'        : "General",
		'info_off_general_description' : ": The General is the pinnacle of the command structure. Leading by example and adhering to a strict code the General is able to inspire great morale in troops, an icon of the military empire the General provides a 20% bonus to Weapons, Shields and Armor technology. <br /><font color=red>+20% Weapons/Shields/Armor</font><br /><font color=red>TOP 50: +10% Weapons/Shields/Armor</font>",
		'info_off_admiral_name'        : "Admiral",
		'info_off_admiral_description' : "The Admiral is an experienced combat veteran skilled in tactical maneuvering. Through strategic management the Admiral grants an increase to all fleet speeds by 20%. The Admiral is also an expert at organizing large combat groups allowing for an additional 2 fleet slots.<br /><font color=red>+2 Fleet Slots and +20% Ship Speed</font><br /><font color=red>TOP 50: +2 Fleet Slots and +10% Ship Speed</font>",
		'info_off_energy_name'        : "Power Engineer",
		'info_off_energy_description' : "The Power Engineer is a specialist in energy management. In peacetime, it increases the energy of all the colonies. In case of attack, ensuring the supply of energy to the cannons, and avoid a possible overload, leading to a reduction in defense lost battle.<br><font color=red>+10% of energy production</font>",
		'info_off_storer_name'        : "The Quartermaster",
		'info_off_storer_description' : "The quartermaster is the epitome of efficiency and logistics. Using the latest in logistic and computational density research the Quartermaster is able to boost storage efficiency across all storage depots on your planets by 20%.<br><font color=green>+20% storage on all planets</font>",
		'info_off_spy_name'        : "Espionage officer",
		'info_off_spy_description' : "The Espionage officer is an expert at persuasion, blackmail, and intelligence gathering. Using these skills along with their vast connections in the underground and black markets, the espionage officer is able to boost intelligence gathering on all spy missions.<br><font color=green>+2 espionage technology</font>",
		'info_off_exspy_name'        : "Counter espionage officer",
		'info_off_exspy_description' : "The Counter-Espionage officer is the uncorruptible detective of all things destabilizing and subversive. With unique skills in codebreaking and untangling lies. The counter-espionage agent is able to corrupt the data on incoming spy missions.<br><font color=green>-2 espionage technology to anyone who spies on you.</font>",
		
		
		
		'mg_type_0'    						: 'Spy reports',
		'mg_type_1'    						: 'Private messages',
		'mg_type_2'    						: 'Alliance messages',
		'mg_type_3'    						: 'Battle reports',
		'mg_type_4'    						: 'Recycling reports',
		'mg_type_5'    						: 'Transportation reports',
		'mg_type_15'   						: 'Expedition reports',
		'mg_type_99'   						: 'Construction reports',
		'mg_type_100'  						: 'View all Messages',
		'mg_no_subject'						: 'No Subject',
		'mg_no_text'							: 'No message',
		'mg_msg_sended'						: 'Message sent',
		'mg_delete_marked'					: 'Delete marked messages',
		'mg_delete_unmarked'					: 'Delete all unmarked messages',
		'mg_delete_all'						: 'Delete all messages',
		'mg_show_only_header_spy_reports'	: 'show only partial espionage reports ',
		'mg_action'							: 'Action',
		'mg_date'							: 'Date',
		'mg_from'							: 'From',
		'mg_subject'							: 'Subject',
		'mg_confirm_delete'					: 'Confirm',
		'mg_message_title'					: 'Messages',
		'mg_message_type'					: 'Message type',
		'mg_total'							: 'Total',
		'mg_game_operators'					: 'Game operators',
		'mg_to'								: 'To',
		'mg_send_message'					: 'Send message',
		'mg_message'							: 'Message',
		'mg_chars'							: 'characters',
		'mg_send'							: 'Send',
		
		
		'al_description_message'				: 'Alliance description message',
		'al_web_text'						: 'Alliance web site',
		'al_request'							: 'Application',
		'al_click_to_send_request'			: 'Apply to the Alliance',
		'al_tag_required'					: 'Alliance tag missing',
		'al_name_required'					: 'Alliance name missing',
		'al_already_exists'					: 'The alliance %s already exists.',
		'al_created'							: 'The alliance %s was created',
		'al_continue'						: 'continue',
		'al_alliance_closed'					: 'This alliance does not support more members',
		'al_request_confirmation_message'	: 'Application registered. Will receive a message when your application is approved / rejected.',
		'al_default_request_text'			: 'The alliance leaders have not set an example of application, or have no pretensions.',
		'al_write_request'					: 'Write application to the alliance %s',
		'al_request_deleted'					: 'Your request to the alliance %s has been deleted. <br/> Now you can write a new application or create your own alliance.',
		'al_request_wait_message'			: 'You\'ve already sent a request to the alliance %s. <br/> Please wait until you receive a reply or delete this application.',
		'al_delete_request'					: 'Delete application',
		'al_founder_cant_leave_alliance'		: 'The founder can not abandon the alliance.',
		'al_leave_sucess'					: 'You leaver the alliance %s succesfully.',
		'al_do_you_really_want_to_go_out'	: 'Do you really want to leave the alliance %s?',
		'al_go_out_yes'						: 'Yes',
		'al_circular_sended'					: 'Circular message sent, Following players will receive your circular message:',
		'al_all_players'						: 'All players',
		'al_no_ranks_defined'				: 'No ranks defined',
		'al_request_text'					: 'Application text',
		'al_inside_text'						: 'Internal text',
		'al_outside_text'					: 'External text',
		'al_transfer_alliance'				: 'Transfer alliance',
		'al_disolve_alliance'				: 'Delete<br/> alliance',
		'al_founder_rank_text'				: 'Founder',
		'al_new_member_rank_text'			: 'New member',
		'al_acept_request'					: 'Accept',
		'al_you_was_acceted'					: 'You was accepted in ',
		'al_hi_the_alliance'					: 'Hello!<br>The alliance <b>',
		'al_has_accepted'					: '</b> accept you application<br>Founder\'s Message: <br>',
		'al_decline_request'					: 'Reject',
		'al_you_was_declined'				: 'You were rejected in ',
		'al_has_declined'					: '</b> the alliance reject your application<br>Founder\'s Message: <br>',
		'al_no_requests'						: 'No requests',
		'al_request_from'					: '"%s\'s" request',
		'al_no_request_pending'				: 'There is %n application/s pending/s',
		'al_name'							: 'name',
		'al_new_name'						: 'New name',
		'al_tag'								: 'tag',
		'al_new_tag'							: 'New tag',
		'al_user_list'						: 'Member List',
		'al_manage_alliance'					: 'Manage alliance',
		'al_send_circular_message'			: 'Send circular message',
		'ally_description_text'				: 'Alliance Description',
		'al_new_requests'					: 'new request/s',
		'al_save'							: 'Save',
		'al_dlte'							: 'Delete',
		'al_rank_name'						: 'Rank name',
		'al_ok'								: 'OK',
		'al_number_of_records'				: 'Total',
		'al_num'								: 'ID',
		'al_member'							: 'Name',
		'al_message'							: 'Message',
		'al_position'						: 'Rank',
		'al_points'							: 'Points',
		'al_coords'							: 'Coords',
		'al_member_since'					: 'Joined',
		'al_estate'							: 'Online',
		'al_back'							: 'Back',
		'al_actions'							: 'Actions',
		'al_change_title'					: 'Change',
		'al_the_alliance'					: 'of the alliance',
		'al_change_submit'					: 'Change',
		'al_reply_to_request'				: 'Reply to request',
		'al_reason'							: 'Reason',
		'al_characters'						: 'characters',
		'al_request_list'					: 'List of requests',
		'al_candidate'						: 'Candidate',
		'al_request_date'					: 'Date of application',
		'al_transfer_alliance'				: 'Resign/take over this alliance?',
		'al_transfer_to'						: 'Transfer to',
		'al_transfer_submit'					: 'Transfer',
		'al_ally_information'				: 'Alliance information',
		'al_ally_info_tag'					: 'Tag',
		'al_ally_info_name'					: 'Name',
		'al_ally_info_members'				: 'Members',
		'al_your_request_title'				: 'Your aplication',
		'al_applyform_send'					: 'Send',
		'al_applyform_reload'				: 'Reload',
		'al_circular_send_ciruclar'			: 'Send circular message',
		'al_receiver'						: 'Recipient',
		'al_circular_send_submit'			: 'Send',
		'al_circular_reset'					: 'Clean',
		'al_alliance'						: 'Alliances',
		'al_alliance_make'					: 'Create Alliance',
		'al_alliance_search'					: 'Search for alliances',
		'al_your_ally'						: 'Your alliance',
		'al_rank'							: 'Your Rank',
		'al_web_site'						: 'Homepage',
		'al_inside_section'					: 'Internal Area',
		'al_make_alliance'					: 'Found alliances',
		'al_make_ally_tag_required'			: 'Alliance Tag (3-8 characters)',
		'al_make_ally_name_required'			: 'Alliance name (3-30 characters)',
		'al_make_submit'						: 'Create',
		'al_find_alliances'					: 'Search for alliances',
		'al_find_text'						: 'Search for',
		'al_find_submit'						: 'search',
		'al_the_nexts_allys_was_founded'		: 'Following alliances were found:',
		'al_manage_ranks'					: 'Configure rights',
		'al_manage_members'					: 'Manage members',
		'al_manage_change_tag'				: 'Change the tag of the alliance',
		'al_manage_change_name'				: 'Change the name of the alliance',
		'al_texts'							: 'Text Management',
		'al_manage_options'					: 'Options',
		'al_manage_image'					: 'Alliance logo',
		'al_manage_requests'					: 'Applications',
		'al_requests_not_allowed'			: 'aren\'t possible(alliance closed)',
		'al_requests_allowed'				: 'are possible(alliance open)',
		'al_manage_founder_rank'				: 'Founder rank',
		'al_configura_ranks'					: 'Configure Rights',
		'al_create_new_rank'					: 'Create New Rank',
		'al_rank_name'						: 'Rank name',
		'al_create'							: 'Create',
		'al_legend'							: 'Rights Description',
		'al_legend_disolve_alliance'			: 'Disband alliance',
		'al_legend_kick_users'				: 'Kick user',
		'al_legend_see_requests'				: 'Show applications',
		'al_legend_see_users_list'			: 'Show member list',
		'al_legend_check_requests'			: 'Process applications',
		'al_legend_admin_alliance'			: 'Manage Alliance',
		'al_legend_see_connected_users'		: 'Show online status in member list',
		'al_legend_create_circular'			: 'Write circular message',
		'al_legend_right_hand'				: '"Right Hand" (necessary to transfer founder rank)',
		
		'al_requests'						: 'Requests',
		'al_circular_message'				: 'Circular message',
		'al_leave_alliance'					: 'Leave this alliance',
		
		
		'bu_request_exists'					: 'There is already an application to that player!',
		'bu_cannot_request_yourself'			: 'You can not ask you as a friend to yourself',
		'bu_request_message'					: 'Request message',
		'bu_player'							: 'Player',
		'bu_request_text'					: 'Application Text',
		'bu_characters'						: 'characters',
		'bu_back'							: 'Back',
		'bu_send'							: 'Send',
		'bu_cancel_request'					: 'Cancel Request',
		'bu_accept'							: 'Accept',
		'bu_decline'							: 'Reject',
		'bu_connected'						: 'Connected',
		'bu_fifteen_minutes'					: '15 minutes',
		'bu_disconnected'					: 'Disconnected',
		'bu_delete'							: 'Delete',
		'bu_buddy_list'						: 'Buddy list',
		'bu_requests'						: 'Applications',
		'bu_alliance'						: 'Alliance',
		'bu_coords'							: 'Coordinates',
		'bu_text'							: 'Text',
		'bu_action'							: 'Action',
		'bu_my_requests'						: 'My Requests',
		'bu_partners'						: 'Partners',
		'bu_estate'							: 'State',
		'bu_deleted_title'					: 'Friend lost',
		'bu_deleted_text'					: 'Player %u has deleted you from their list of friends.',
		'bu_accepted_title'					: 'Request accepted',
		'bu_accepted_text'					: 'Player %u has accepted your friend request.',
		'bu_rejected_title'					: 'Request refused',
		'bu_rejected_text'					: 'Player %u has rejected your friend request.',
		'bu_to_accept_title'					: 'New Friend Request',
		'bu_to_accept_text'					: 'Player %u has sent you a friend request.',
		
		
		'nt_important'						: 'Important',
		'nt_normal'							: 'Normal',
		'nt_unimportant'						: 'Unimportant',
		'nt_create_note'						: 'Create note',
		'nt_edit_note'						: 'Edit note',
		'nt_you_dont_have_notes'				: 'no notes recorded',
		'nt_notes'							: 'Notes',
		'nt_create_new_note'					: 'Create a new note',
		'nt_date_note'						: 'Date',
		'nt_subject_note'					: 'Subject',
		'nt_size_note'						: 'Size',
		'nt_dlte_note'						: 'Delete',
		'nt_priority'						: 'Priority',
		'nt_note'							: 'Notice',
		'nt_characters'						: 'characters',
		'nt_back'							: 'Back',
		'nt_reset'							: 'Reestablecer',
		'nt_save'							: 'Save',
		
		
		'st_player'							: 'Player',
		'st_alliance'						: 'Alliance',
		'st_points'							: 'Points',
		'st_fleets'							: 'Fleet',
		'st_researh'							: 'Research',
		'st_buildings'						: 'Building',
		'st_defenses'						: 'Defense',
		'st_position'						: 'Rank',
		'st_members'							: 'Member',
		'st_per_member'						: 'Per Member',
		'st_statistics'						: 'Statistics',
		'st_updated'							: 'Updated',
		'st_show'							: 'show',
		'st_per'								: 'by',
		'st_in_the_positions'				: 'in ranks',
		
		
		'sh_tag'								: 'Tag',
		'sh_name'							: 'Name',
		'sh_members'							: 'Member',
		'sh_points'							: 'Points',
		'sh_searcg_in_the_universe'			: 'Search Universe',
		'sh_player_name'						: 'Player Name',
		'sh_planet_name'						: 'Planet Name',
		'sh_alliance_tag'					: 'Alliance Tag',
		'sh_alliance_name'					: 'Alliance Name',
		'sh_search'							: 'search',
		'sh_buddy_request'					: 'Buddy request',
		'sh_alliance'						: 'Alliance',
		'sh_planet'							: 'Planet',
		'sh_coords'							: 'Position',
		'sh_position'						: 'Rank',
		
		
		'op_cant_activate_vacation_mode'		: 'If you\'re building or moving fleets will not be able to enter on vacation mode.',
		'op_password_changed'				: 'Password has been changed.',
		'op_username_changed'				: 'Username changed.',
		'op_options_changed'					: 'Changes saved.',
		'op_vacation_mode_active_message'	: 'The vacation mode is turned on. Have to be on vacation at least until: ',
		'op_end_vacation_mode'				: 'Finish vacation mode',
		'op_save_changes'					: 'save changes',
		'op_admin_title_options'				: 'Options available to management',
		'op_admin_planets_protection'		: 'Protection of planets',
		'op_user_data'						: 'User Data',
		
		'op_username'						: 'Username',
		'op_old_pass'						: 'Old password',
		'op_new_pass'						: 'New password (min. 8 characters)',
		'op_repeat_new_pass'					: 'New password (repeat)',
		'op_email_adress'					: 'Email address',
		'op_permanent_email_adress'			: 'Permanent Address',
		'op_general_settings'				: 'General Options',
		'op_sort_planets_by'					: 'Sort planets by:',
		'op_sort_kind'						: 'Assortment sequence:',
		'op_skin_example'					: 'Skin',
		'op_show_skin'						: 'Display skin',
		'op_deactivate_ipcheck'				: 'Disable IP Check',
		'op_galaxy_settings'					: 'Galaxy View Options',
		'op_spy_probes_number'				: 'Number of espionage probes',
		'op_toolt_data'						: 'Information tools',
		'op_seconds'							: 'seconds',
		'op_max_fleets_messages'				: 'Maximum fleet messages',
		'op_show_ally_logo'					: 'Display ally logo',
		'op_shortcut'						: 'Shortcut',
		'op_show'							: 'Show',
		'op_spy'								: 'Spy',
		'op_write_message'					: 'Write message',
		'op_add_to_buddy_list'				: 'Add to buddylist',
		'op_missile_attack'					: 'Missile attack',
		'op_send_report'						: 'Send report',
		'op_vacation_delete_mode'			: 'Vacation mode (Be careful you can\'t leave vacation mode in the first 72 hours)',
		'op_activate_vacation_mode'			: 'Enable vacation mode',
		'op_dlte_account'					: 'Delete account',
		'op_email_adress_descrip'			: 'You can change this email address at any time. This will be entered as a permanent address after 7 days without changes.',
		'op_deactivate_ipcheck_descrip'		: 'IP check means that a security logout occurs automatically when the IP changes or two people are logged into an account from different IPs. Disabling the IP check may represent a security risk!',
		'op_spy_probes_number_descrip'		: 'Number of espionage probes that can be sent directly from each scan in the Galaxy menu.',
		'op_activate_vacation_mode_descrip'	: 'Vacation mode will protect you during long absences. It can only be activated if nothing is being built (fleet, building, or defense), nothing is being researched, and none of your fleets are underway. Once it is activated, you are protected from new attacks. Attacks that have already started will be carried out. During vacation mode, production is set to zero and must be manually returned to 100 % after vacation mode ends. Vacation mode lasts a minimum of two days and can only be deactivated after this time.',
		'op_dlte_account_descrip'			: 'If you mark this box, your account will be deleted automatically after 7 days.',
		'op_sort_colonization'				: 'Colonization Date',
		'op_sort_coords'						: 'Coordinates',
		'op_sort_alpha'						: 'Alphabetic order',
		'op_sort_asc'						: 'Ascendant',
		'op_sort_desc'						: 'Decreasing',
		
		
		'bn_no_players_banned'				: 'No banned players',
		
		'bn_exists'							: 'Exists ',
		'bn_players_banned'					: ' player/s banned/s',
		'bn_players_banned_list'				: 'List of banned players',
		'bn_player'							: 'Player',
		'bn_reason'							: 'Reason',
		'bn_from'							: 'From',
		'bn_until'							: 'Until',
		'bn_by'								: 'By',
		
		
		'sys_attacker_lostunits' 			: "The attacker has lost a total of",
		'sys_defender_lostunits' 			: "The defender has lost a total of",
		'sys_units'							: "units",
		'debree_field_1' 					: "A debris field",
		'debree_field_2'						: "floating in the orbit of the planet.",
		'sys_moonproba' 						: "The probability that a moon emerge from the rubble is:",
		'sys_moonbuilt' 						: "The huge amount of metal and glass are functioning and form a lunar satellite in orbit the planet %s %d:%d:%d !",
		'sys_attack_title'    				: "Fleets clash in ",
		'sys_attack_round'					: "Round",
		'sys_attack_attacker_pos' 			: "Aggressor",
		'sys_attack_techologies' 			: "Weapons: %d %% Shield: %d %% Armor: %d %% ",
		'sys_attack_defender_pos' 			: "Defender",
		'sys_ship_type' 						: "Type",
		'sys_ship_count' 					: "Amount",
		'sys_ship_weapon' 					: "Weapons",
		'sys_ship_shield' 					: "Shield",
		'sys_ship_armour' 					: "Armor",
		'sys_destroyed' 						: "Destroyed",
		'fleet_attack_1' 					: "The attacking fleet fires a total force of",
		'fleet_attack_2'						: "on the defender. The defender's shields absorb",
		'fleet_defs_1' 						: "The defending fleet fires a total force of",
		'fleet_defs_2'						: "on the attacker. The attacker's shields absorb",
		'damage'								: "points of damage.",
		'sys_attacker_won' 					: "The attacker has won the battle",
		'sys_defender_won' 					: "The defender has won the battle",
		'sys_both_won' 						: "The battle ended in a draw",
		'sys_stealed_ressources' 			: "obtaining",
		'sys_and'							: "and",
		'sys_mess_tower' 					: "Control Tower",
		'sys_mess_attack_report' 			: "Battle Report",
		'sys_spy_maretials' 					: "Resources",
		'sys_spy_fleet' 						: "Fleet",
		'sys_spy_defenses' 					: "Defense",
		'sys_mess_qg' 						: "Headquarters",
		'sys_mess_spy_report_moon'			: "(Moon)",
		'sys_mess_spy_report' 				: "Report espionage",
		'sys_mess_spy_lostproba' 			: "Probability of detection of the fleet of spy : %d %% ",
		'sys_mess_spy_control' 				: "Space Control",
		'sys_mess_spy_activity' 				: "Espionage activity",
		'sys_mess_spy_ennemyfleet' 			: "An enemy fleet on the planet",
		'sys_mess_spy_seen_at' 				: "was seen near your planet",
		'sys_mess_spy_destroyed' 			: "Your fleet has been destroyed espionage",
		'sys_stay_mess_stay' 				: "Parking Fleet",
		'sys_stay_mess_start' 				: "your fleet arrives on the planet",
		'sys_stay_mess_end' 					: " and offers the following resources : ",
		'sys_adress_planet' 					: "%s:%s:%s",
		'sys_stay_mess_goods' 				: "%s : %s, %s : %s, %s : %s",
		'sys_colo_mess_from' 				: "Colonization",
		'sys_colo_mess_report' 				: "Report of settlement",
		'sys_colo_defaultname' 				: "Colony",
		'sys_colo_arrival' 					: "The settlers arrived at cordenadas ",
		'sys_colo_maxcolo' 					: ", but, unfortunately, can not colonize, can have no more ",
		'sys_colo_allisok' 					: ", 	the settlers are beginning to build a new colony.",
		'sys_colo_badpos'  					: ", 	the settlers have found an environment conducive to the expansion of its empire. They decided to reverse totally disgusted ...",
		'sys_colo_notfree' 					: ", 	settlers would not have found a planet with these details. They are forced to turn back completely demoralized ...",
		'sys_colo_planet'  					: " planet ",
		'sys_expe_report' 					: "Report of expedition",
		'sys_recy_report' 					: "Recycling Report",
		'sys_expe_blackholl_1' 				: "The fleet was sucked into a black hole is partially destroyed.",
		'sys_expe_blackholl_2' 				: "The fleet was sucked into a black hole, and was completely destroyed!",
		'sys_expe_nothing_1' 				: "Your explorers took great photos. But resources have not found",
		'sys_expe_nothing_2' 				: "Your scouts have spent the time in the selected area. But they have not found anything.",
		'sys_expe_found_goods' 				: "The fleet has discovered an unmanned spacecraft! <br>  His scouts have recovered %s of %s, %s of %s, %s of %s and %s of %s.",
		'sys_expe_found_ships' 				: "Your scouts have found an abandoned squad, dominated it and come back. <br> Squadron:",
		'sys_expe_back_home' 				: "Your expedition returned to the hangar.",
		'sys_mess_transport' 				: "Transport Fleet",
		'sys_tran_mess_owner' 				: "One of your fleet reaches %s %s and deliver their goods: %s of %s, %s of %s and %s of %s.",
		'sys_tran_mess_user'  				: "Fleet from %s %s deliver their goods to %s %s.<br/> Resources delivered:<br/>%s%s<br/>%s%s<br/>%s%s",
		'sys_mess_fleetback' 				: "Return of the fleet",
		'sys_tran_mess_back' 				: "A fleet back to planet % s% s. The fleet does not give resources.",
		'sys_recy_gotten' 					: "Your fleet arrived at the coordinates indicated and gatherers %s units %s and %s units of %s.",
		'sys_notenough_money' 				: "You do not have enough resources to build a %s. You %s of %s, %s of %s and %s of %s and the cost of construction was %s of %s, %s of %s and %s of %s",
		'sys_nomore_level' 					: "You try to destroy a building ( %s ).",
		'sys_buildlist' 						: "List of building area",
		'sys_buildlist_fail' 				: "Construcion impossible",
		'sys_gain' 							: "Benefits",
		'sys_fleet_won' 						: "One of your fleets returning from the planet %s %s and delivery %s of %s, %s of %s and %s of %s",
		'sys_perte_attaquant' 				: "Forward Party",
		'sys_perte_defenseur' 				: "Part Defender",
		'sys_debris' 						: "Debris",
		'sys_destruc_title'    				: "Probability of kill moon %s :",
		'sys_mess_destruc_report' 			: "Destruction Report",
		'sys_destruc_lune' 					: "The probability of destroying the moon is: %d %% ",
		'sys_destruc_rip' 					: "The probability that the stars of death are destroyed is: %d %% ",
		'sys_destruc_stop' 					: "The defender has failed to stop the destruction of the moon",
		'sys_destruc_mess1' 					: "The shooting death stars the graviton to the orbit of the moon",
		'sys_destruc_mess' 					: "A fleet of the planet %s %d:%d:%d goes to the moon of the planet %d:%d:%d",
		'sys_destruc_echec' 					: ". The tremors began to shake off the surface of the moon, but something goes wrong, the graviton in the stars of death also causes tremors and death stars fly to pieces.",
		'sys_destruc_reussi' 				: ", The tremors began to shake off the surface of the moon, after a while the moon does not support more and fly to pieces, mission accomplished, the fleet returns to home planet.",
		'sys_destruc_null' 					: ", The stars of death did not generate the power, the mission fails and the ships returned home.",
		'sys_the'							: " the ",
		'sys_stay_mess_back'         		: "One of your fleet return from ",
		'sys_stay_mess_bend'         		: " and offers ",
		
		
		'ccs_multiple_users'					: 'Cookie error! There are several users with this name! You must delete your cookies. In case of problems contact the administrator.',
		'ccs_other_user'						: 'Cookie error! Your cookie does not match the user! You must delete your cookies. In case of problems contact the administrator',
				
		
		
		'cff_no_fleet_data'					: 'No fleet data',
		'cff_aproaching'						: 'They approach ',
		'cff_ships'							: ' ships',
		'cff_from_the_planet'				: 'from the planet ',
		'cff_from_the_moon'					: 'from the moon ',
		'cff_the_planet'						: 'the planet ',
		'cff_debris_field'					: 'debris field ',
		'cff_to_the_moon'					: 'to the moon ',
		'cff_the_position'					: 'position ',
		'cff_to_the_planet'					: ' to planet ',
		'cff_the_moon'						: ' the moon ',
		'cff_from_planet'					: 'the planet ',
		'cff_from_debris_field'				: 'the debris field ',
		'cff_from_the_moon'					: 'of the moon ',
		'cff_from_position'					: 'position ',
		'cff_missile_attack'					: 'Missile attack',
		'cff_from'							: ' from ',
		'cff_to'								: ' to ',
		'cff_one_of_your'					: 'One of your ',
		'cff_a'								: 'One ',
		'cff_of'								: ' of ',
		'cff_goes'							: ' goes ',
		'cff_toward'							: ' toward ',
		'cff_with_the_mission_of'			: '. With the mission of: ',
		'cff_to_explore'						: ' to explore ',
		'cff_comming_back'					: ' comes back from ',
		'cff_back'							: 'Comming back',
		'cff_to_destination'					: 'Heading to destination',
		'cff_flotte' 						: " fleets",
		
		
		'fcm_moon'							: 'Moon',
		'fcp_colony'							: 'Colony',
		'fgp_require'						: 'Requires: ',
		'fgp_cost'							: 'Cost: ',
		'fgf_time'							: 'Construction Time: ',
		
		
		
		'cr_lost_contact'					: 'Contact was lost with the attacking fleet.',
		'cr_first_round'						: '(The fleet was destroyed in the first round)',
		'cr_type'							: 'Type',
		'cr_total'							: 'Total',
		'cr_weapons'							: 'Weapons',
		'cr_shields'							: 'Shields',
		'cr_armor'							: 'Armor',
		'cr_destroyed'						: 'Destroyed!',
		
		
		'fa_not_enough_probes'				: 'Error, no sufficient probes',
		'fa_galaxy_not_exist'				: 'Error, the galaxy does not exist',
		'fa_system_not_exist'				: 'Error, the system does not exist',
		'fa_planet_not_exist'				: 'Error, the planet does not exist',
		'fa_not_enough_fuel'					: 'Error, you do not have enough fuel',
		'fa_no_more_slots'					: 'Error, you have no more slots available fleet',
		'fa_no_recyclers'					: 'Error, recyclers are not available',
		'fa_mission_not_available'			: 'Error, the mission is not available',
		'fa_no_ships'						: 'Error, no available ships',
		'fa_vacation_mode'					: 'Error, the player is in vacation mode',
		'fa_week_player'						: 'Error, the player is too weak',
		'fa_strong_player'					: 'Error, the player is too strong',
		'fa_not_spy_yourself'				: 'Error, can not spy on yourself',
		'fa_not_attack_yourself'				: 'Error, can not attack yourself',
		'fa_action_not_allowed'				: 'Error, action not permitted',
		'fa_vacation_mode_current'			: 'Error, you are in vacation mode',
		'fa_sending'							: 'Fleet has been sent<br/>',
		
		
		'ma_silo_level'						: 'You must be at least level 4 silo',
		'ma_impulse_drive_required'			: 'You must investigate the Impulse Drive.',
		'ma_not_send_other_galaxy'			: 'You can not send missiles to another galaxy.',
		'ma_planet_doesnt_exists'			: 'The objective world does not exist.',
		'ma_cant_send'						: 'You can not send ',
		'ma_missile'							: ' missiles, have only ',
		'ma_wrong_target'					: 'Wrong Target',
		'ma_no_missiles'						: 'There are no available Interplanetary Missile',
		'ma_add_missile_number'				: 'Enter the number of missiles that you want to send',
		'ma_misil_launcher'					: 'Rocket Launcher',
		'ma_small_laser'						: 'Light Laser',
		'ma_big_laser'						: 'Heavy Laser',
		'ma_gauss_canyon'					: 'Gauss Cannon',
		'ma_ionic_canyon'					: 'Ion Cannon',
		'ma_buster_canyon'					: 'Plasma Turret',
		'ma_small_protection_shield'			: 'Small Shield Dome',
		'ma_big_protection_shield'			: 'Large Shield Dome',
		'ma_all'								: 'All',
		'ma_missiles_sended'					: ' interplanetary missiles were sent. Main objective: ',
		'ma_all_destroyed' 					:'All interplanetary missiles has been destoyed by interceptor missiles.',
		'ma_planet_without_defens'  			:'Planet without dedenses',
		'ma_some_destroyed'   				:' has been destroyed by interceptor missiles.',
		'ma_missile_attack'					:'',
		'ma_missile_string'					:'Missiles attack (%1%) from %2% arrive to planet %3% <br><br>',
		
		
		'Chat'  : "Tchat",
		'chat_title'                         : 'Chat',
		'chat_ally_title'                    : 'Alliance chat',
		'chat_loading'  : "Loading...",
		'chat_disc'     : "Discursion",
		'chat_message'  : "Messages",
		'chat_short'    : "Shortcuts",
		'chat_text'     : "Text",
		'chat_send'     : "Send",
		
		'end_line':''
	}
};